"""New fields added in User

Revision ID: 24859f58b0df
Revises: 6cc66b4a8b37
Create Date: 2018-05-06 13:25:17.842972

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24859f58b0df'
down_revision = '6cc66b4a8b37'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('about_me', sa.String(length=140), nullable=True))
    op.add_column('user', sa.Column('last_seen', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_seen')
    op.drop_column('user', 'about_me')
    # ### end Alembic commands ###
